name: Extract Branch Name
description: Extract the branch name from the GitHub event
outputs:
  branch_name:
    description: 'The name of the branch'
runs:
  using: 'composite'
  steps:
    - name: Extract branch name
      id: extract_branch
      shell: bash
      run: |
        if [ "${{ github.event_name }}" == "pull_request" ]; then
          echo "BRANCH_NAME=${{ github.head_ref }}" >> $GITHUB_ENV
          echo "::set-output name=branch_name::${{ github.head_ref }}"
        else
          echo "BRANCH_NAME=${{ github.ref_name }}" >> $GITHUB_ENV
          echo "::set-output name=branch_name::${{ github.ref_name }}"
        fi