name: Gradle Test

on:
  pull_request:
    branches:
      - main
      - develop
      - feature/*

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up JDK 21
      uses: actions/setup-java@v2
      with:
        distribution: 'temurin'
        java-version: '21'

    - name: Grant execute permission for gradlew
      run: chmod +x ./java-boardgames-api/gradlew

    - name: Build with Gradle
      run: ./java-boardgames-api/gradlew build

    - name: Run tests
      run: ./java-boardgames-api/gradlew test
      