name: Java CI

on:
  pull_request:
    branches:
      - main
  workflow_dispatch:

env:
  K8S_NAMESPACE: java-boardgames-api
  APP_NAME: java-boardgames-api 
  WORKING_DIR: java-boardgames-api    

jobs:
  build:
    runs-on: ubuntu-latest
    steps:

    - name: Checkout sources
      uses: actions/checkout@v4

    - name: Setup Java
      uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: 21

    - name: Setup Gradle
      uses: gradle/actions/setup-gradle@v4

    - name: Build with Gradle
      run: ./gradlew build
      working-directory: ./${{ env.WORKING_DIR }}

  build-image-push:
    runs-on: ubuntu-latest
    needs: build

    env:
      BRANCH_NAME: ''

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Call composite action to extract branch name
      id: extract-branch-name
      uses: david-gimelle/lab/.github/actions/extract-branch-name@main

    - name: Set branch name from composite action
      run: echo "BRANCH_NAME=${{ steps.extract-branch-name.outputs.branch_name }}" >> $GITHUB_ENV

    - name: Display branch name from composite action
      run: echo "Branch name is ${{ env.BRANCH_NAME }}"       

    - name: Log in to GitHub Docker registry
      run: echo "${{ secrets.GHCR_PAT }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin
      
    - name: Build Docker image
      run: |
        docker build -t ./${{ env.APP_NAME }}:${{ env.BRANCH_NAME }} .
      working-directory: ./${{ env.WORKING_DIR }}  

    - name: Tag Docker image
      run: |
        docker tag ${{ env.APP_NAME }}:${{ env.BRANCH_NAME }} ghcr.io/${{ github.repository }}/${{ env.APP_NAME }}:${{ env.BRANCH_NAME }}

    - name: Push Docker image to GitHub Packages
      run: |
        docker push ghcr.io/${{ github.repository }}/${{ env.APP_NAME }}:${{ env.BRANCH_NAME }}
