name: Python Release

on:
  workflow_run:
    workflows: ["Python CI"]
    types:
      - completed
  workflow_dispatch:

jobs:
  create-release:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Git
      run: |
        git config --global user.email "github-actions[bot]@users.noreply.github.com"
        git config --global user.name "github-actions[bot]"

    - name: Create Tag
      id: create_tag
      env:
        GH_PAT: ${{ secrets.GH_PAT }}
      run: |
        TAG_NAME="v$(date +'%Y%m%d%H%M%S')"
        echo "Generated tag name: ${TAG_NAME}"
        echo "TAG_NAME=${TAG_NAME}" >> $GITHUB_ENV
        echo "Pushing tag to repository: https://x-access-token:${{ secrets.GH_PAT }}@github.com/${{ github.repository }}"
        git tag $TAG_NAME
        git push https://x-access-token:${{ secrets.GH_PAT }}@github.com/${{ github.repository }} $TAG_NAME

    - name: Create GitHub Release
      if: github.event_name == 'workflow_dispatch' || (github.event.workflow_run.conclusion == 'success' && github.event.workflow_run.head_branch == 'main' && github.event.workflow_run.event == 'pull_request')
      uses: actions/create-release@v1
      with:
        tag_name: ${{ env.TAG_NAME }}
        release_name: Release ${{ env.TAG_NAME }}
        body: |
          Release notes for ${{ env.TAG_NAME }}
      env:
        GITHUB_TOKEN: ${{ secrets.GH_PAT }}