name: Python Release

on:
  workflow_run:
    workflows: ["Python CI"]
    types:
      - completed
  workflow_dispatch:

jobs:
  create-release:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        token: ${{ secrets.GH_PAT }}

    - name: Set up Git
      run: |
        git config --global user.email "github-actions[bot]@users.noreply.github.com"
        git config --global user.name "github-actions[bot]"

    - name: Create Tag
      id: create_tag
      run: |
        TAG_NAME="v$(date +'%Y%m%d%H%M%S')"
        echo "Generated tag name: ${TAG_NAME}"
        echo "TAG_NAME=${TAG_NAME}" >> $GITHUB_ENV
        echo "GH_PAT value: ${{ secrets.GH_PAT }}"  # This will be masked in the logs
        echo "Number of characters in GH_PAT: ${#GH_PAT}"
        if [[ ${{ secrets.GH_PAT }} == ghp* ]]; then echo "GH_PAT token starts with 'ghp'"; else echo "GH_PAT token does not start with 'ghp'"; fi
        if [[ ${{ secrets.GH_PAT }} == *JgF ]]; then echo "GH_PAT token ends with 'JgF'"; else echo "GH_PAT token does not end with 'JgF'"; fi
        echo "Pushing tag to repository"
        git tag $TAG_NAME
        git push origin $TAG_NAME

    - name: Create GitHub Release
      if: github.event_name == 'workflow_dispatch' || (github.event.workflow_run.conclusion == 'success' && github.event.workflow_run.head_branch == 'main' && github.event.workflow_run.event == 'pull_request')
      uses: actions/create-release@v1
      with:
        tag_name: ${{ env.TAG_NAME }}
        release_name: Release ${{ env.TAG_NAME }}
        body: |
          Release notes for ${{ env.TAG_NAME }}
      env:
        GITHUB_TOKEN: ${{ secrets.GH_PAT }}