name: Python CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

env:
  K8S_NAMESPACE: python-boardgames-api
  K8S_SERVICE_NAME: python-boardgames-api-service
  APP_NAME: python-boardgames-api 
  WORKING_DIR: python-boardgames-api

jobs:
  build:
    runs-on: ubuntu-latest
    outputs:
      APP_NAME: ${{ env.APP_NAME }}
      WORKING_DIR: ${{ env.WORKING_DIR }}
      K8S_NAMESPACE: ${{ env.K8S_NAMESPACE }}
      K8S_SERVICE_NAME: ${{ env.K8S_SERVICE_NAME }}

    steps:
    - name: Checkout code
      uses: actions/checkout@v4 

    - name: Set up Python
      uses: actions/setup-python@v4 
      with:
        python-version: '3.x'

    - name: Install Poetry
      run: |
        curl -sSL https://install.python-poetry.org | python3 -
        echo "export PATH=$HOME/.local/bin:$PATH" >> $GITHUB_ENV
      working-directory: ${{ env.WORKING_DIR }}

    - name: Install dependencies
      run: |
        poetry install --no-root
      working-directory: ${{ env.WORKING_DIR }}

    - name: Run install-build.py with --skip-install-poetry to build image
      run: |
        python install-build.py --skip-install-poetry
      working-directory: ${{ env.WORKING_DIR }}  

    - name: Run tests
      run: |
        poetry run pytest
      working-directory: ${{ env.WORKING_DIR }}  

  call-build-image-push:
        uses: david-gimelle/lab/.github/workflows/build-image-push-to-ghcr.yml@main
        needs: build
        
        with:
          APP_NAME: ${{ needs.build.outputs.APP_NAME }}
          WORKING_DIR: ${{ needs.build.outputs.WORKING_DIR }}
        secrets:
          GHCR_PAT: ${{ secrets.GHCR_PAT }}

  deploy-webservice-to-gke:
      uses: david-gimelle/lab/.github/workflows/deploy-web-service-to-gke.yml@main
      needs: [build, call-build-image-push]

      with:
          k8s_namespace: ${{ needs.build.outputs.K8S_NAMESPACE }}
          k8s_service_name: ${{ needs.build.outputs.K8S_SERVICE_NAME }}
          app_name: ${{ needs.build.outputs.APP_NAME }}
          gke_cluster_name: ${{ vars.GKE_CLUSTER_NAME_PYTHON }}
          gke_cluster_zone: ${{ vars.GKE_CLUSTER_ZONE }}
          gcp_project_id: ${{ vars.GCP_PROJECT_ID }}
      secrets:    
          ghcr_pat: ${{ secrets.GHCR_PAT }}
          gcp_sa_key: ${{ secrets.GCP_SA_KEY }}