name: Reactjs CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

env:
  K8S_NAMESPACE: reactjs-boardgames-api
  K8S_SERVICE_NAME: reactjs-boardgames-api-service
  APP_NAME: reactjs-boardgames-api 
  WORKING_DIR: reactjs-boardgames-api 
  PORT: 8282

jobs:
  build:
    runs-on: ubuntu-latest
    outputs:
      APP_NAME: ${{ env.APP_NAME }}
      WORKING_DIR: ${{ env.WORKING_DIR }}
      K8S_NAMESPACE: ${{ env.K8S_NAMESPACE }}
      K8S_SERVICE_NAME: ${{ env.K8S_SERVICE_NAME }}
      PORT: ${{ env.PORT }}
      TIMESTAMP: ${{ steps.set-timestamp.outputs.timestamp }}

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '16'

    - name: Install dependencies
      run: npm install
      working-directory: ./reactjs-boardgames

    - name: Build the project
      run: npm run build
      working-directory: ./reactjs-boardgames

    - name: Run tests
      run: npm test
      working-directory: ./reactjs-boardgames

  call-build-image-push:
        uses: david-gimelle/lab/.github/workflows/build-image-push-to-ghcr.yml@main
        needs: build
        
        with:
          APP_NAME: ${{ needs.build.outputs.APP_NAME }}
          WORKING_DIR: ${{ needs.build.outputs.WORKING_DIR }}
          timestamp: ${{ needs.build.outputs.TIMESTAMP }}
        secrets:
          GHCR_PAT: ${{ secrets.GHCR_PAT }}      