name: Terraform React App

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:
    
jobs:
  terraform:
    runs-on: ubuntu-latest
    env:
      ARM_ACCESS_KEY: ${{ secrets.AZURE_STORAGE_ACCESS_KEY }}
      ARM_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
      ARM_CLIENT_SECRET: ${{ secrets.AZURE_CLIENT_SECRET }}
      ARM_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
      ARM_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Debug Directory Structure
      run: |
        echo "Current directory: $(pwd)"
        echo "Directory contents:"
        ls -la
        echo "Terraform directory structure:"
        find ./terraform -type d
        echo "React directory contents:"
        ls -la ./terraform/envs/dev/react || echo "React directory not found"

    - name: Set up Terraform
      uses: hashicorp/setup-terraform@v2
      with:
        terraform_version: 1.0.0

    - name: Azure Login
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}
      continue-on-error: false

    - name: Check and Remove Terraform Lock
      run: |
        echo "Attempting to remove state lock..."
        terraform force-unlock -force dc350cbf-0075-db54-c8a0-f61bcc9dab49
      working-directory: ./terraform/envs/dev/react
      continue-on-error: true    

    - name: Terraform Init
      run: TF_LOG=INFO terraform init
      working-directory: ./terraform/envs/dev/react
     
    - name: Terraform Plan  
      run: TF_LOG=TRACE terraform plan
      working-directory: ./terraform/envs/dev/react