name: Terraform React App

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:
    
jobs:
  terraform:
    runs-on: ubuntu-latest
    env:
      ARM_ACCESS_KEY: ${{ secrets.AZURE_STORAGE_ACCESS_KEY }}
      ARM_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
      ARM_CLIENT_SECRET: ${{ secrets.AZURE_CLIENT_SECRET }}
      ARM_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
      ARM_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
      TF_VAR_client_id: ${{ secrets.AZURE_CLIENT_ID }}
      TF_VAR_client_secret: ${{ secrets.AZURE_CLIENT_SECRET }}
      TF_VAR_subscription_id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
      TF_VAR_tenant_id: ${{ secrets.AZURE_TENANT_ID }}
      TF_VAR_resource_group_name: ${{ vars.AZ_RESOURCE_GROUP }}

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Create Terraform Variables
      run: |
        cat > ./terraform/envs/dev/react/terraform.tfvars <<EOF
        client_id       = "${{ secrets.AZURE_CLIENT_ID }}"
        client_secret   = "${{ secrets.AZURE_CLIENT_SECRET }}"
        tenant_id       = "${{ secrets.AZURE_TENANT_ID }}"
        subscription_id = "${{ secrets.AZURE_SUBSCRIPTION_ID }}"
        resource_group_name = "${{ vars.AZ_RESOURCE_GROUP }}"
        EOF
      working-directory: .

    - name: Set up Terraform
      uses: hashicorp/setup-terraform@v2
      with:
        terraform_version: 1.0.0

    - name: Azure Login
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}
        enable-AzPSSession: true
      continue-on-error: false 
      
      
    - name: Verify Azure Permissions
      run: |
        az account show
        az aks list --resource-group ${{ vars.AZ_RESOURCE_GROUP }}
      continue-on-error: true

    - name: Terraform Init
      run: TF_LOG=INFO terraform init
      working-directory: ./terraform/envs/dev/react
    
    - name: Check and Remove Terraform Lock
      run: |
        echo "Attempting to remove state lock..."
        terraform force-unlock -force 30dd4f6c-b7be-1f1f-34c9-c3843ace2b56
      working-directory: ./terraform/envs/dev/react
      continue-on-error: true     

    - name: Terraform Plan  
      run: TF_LOG=INFO terraform plan
      working-directory: ./terraform/envs/dev/react
