name: Unit Tests Every Projects

on:
  push:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Install Python dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r python-boardgames-api/requirements.txt

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '14'

    - name: Install Node.js dependencies for React project
      run: npm install
      working-directory: reactjs-boardgames

    - name: Install Node.js dependencies for Node.js project
      run: npm install
      working-directory: nodejs-boardgames-api

    - name: Set up Java
      uses: actions/setup-java@v2
      with:
        distribution: 'adopt'
        java-version: '11'

    - name: Grant execute permissions for test_all.py
      run: chmod +x test_all.py

    - name: Run test_all.py script
      run: python test_all.py